# Generated by Django 5.0 on 2024-03-31 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sobrenome', models.CharField(max_length=50)),
                ('cpf', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_material', models.CharField(max_length=50)),
                ('unidade_material', models.CharField(max_length=50)),
                ('quantidade', models.IntegerField()),
                ('doacoes', models.IntegerField(default=0)),
                ('doador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='doador.doador')),
            ],
        ),
    ]
