# Generated by Django 5.0 on 2024-04-02 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doador', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doador',
            name='email',
            field=models.EmailField(default=0, max_length=50),
            preserve_default=False,
        ),
    ]
